#TODO --- Define this image to inherit from the "ubuntu" base image
#https://hub.docker.com/_/ubuntu
#https://docs.docker.com/engine/reference/builder/#from

#TODO --- Copy source code in the ./code directory into /opt/gowebapp
#https://docs.docker.com/engine/reference/builder/#copy

EXPOSE 80

#TODO --- Copy the application config in the ./config directory into
#/opt/gowebapp/config


#TODO --- Define an entrypoint for this image which executes the gowebapp
#application (/opt/gowebapp/gowebapp) when the container starts
#https://docs.docker.com/engine/reference/builder/#entrypoint
