# Create a service account for Helm and grant the cluster admin role.
# It is assumed that helm should be installed with this service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nsadmin
  namespace: shawnho
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: shawnho 
  name: shawnho-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nsadmin
  namespace: shawnho 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shawnho-role
subjects:
- kind: ServiceAccount
  name: nsadmin
  namespace: shawnho
