apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp-mysql
spec:
  selector:
    matchLabels:
      app: gowebapp-mysql
  template:
    metadata:
      labels:
        app: gowebapp-mysql
    spec:
      containers:
      - name: gowebapp-mysql
        image: shawnho1976/gowebapp-mysql:v1.2
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: gowebapp-mysql
spec:
  selector:
    app: gowebapp-mysql
  ports:
  - port: 3306
    targetPort: 3306

