apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: shawnho1976/gowebapp:v1.0
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp-sql
spec:
  selector:
    matchLabels:
      app: gowebapp-sql
  template:
    metadata:
      labels:
        app: gowebapp-sql
    spec:
      containers:
      - name: gowebapp-sql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "VMware1!"
        image: shawnho1976/gowebapp-sql:v1.0
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: webservice
spec:
  selector:
    app: webserver
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80


